# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  environment.systemPackages = [ pkgs.sbctl ];

  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.timeout = 1;

  boot.lanzaboote =
    { enable = true;
      pkiBundle = "/var/lib/sbctl";
    };

  boot.initrd = 
    { systemd.enable = true;
      verbose = false;
      availableKernelModules = [ "amdgpu" "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ "dm-snapshot" ];
      luks.devices."root-nvme".device = "/dev/disk/by-uuid/1c9c2d27-ebeb-4069-9bfc-9f98052ee4c3";
      luks.devices."root-sata".device = "/dev/disk/by-uuid/8dba8988-0ca0-4d99-b864-cd531c2c802d";
    };

  boot.plymouth =
    { enable = true;
      theme = "tech_b";
      themePackages = with pkgs; [
        (adi1090x-plymouth-themes.override {
	        selected_themes = [ "tech_b" ];
	      })
      ];
    };

  boot.bootspec.enable = true;

  boot.consoleLogLevel = 3;
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [
    "quiet"
    "splash"
    "boot.shell_on_fail"
    "udev.log_priority=3"
    "rd.systemd.show_status=auto"
    "zswap.enabled=1"
    "zswap.compressor=lz4"
    "zswap.max_pool_percent=20"
  ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a4c75369-0a40-4792-80e2-e3bdf21baf4e";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/264E-EDE6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a4c75369-0a40-4792-80e2-e3bdf21baf4e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a4c75369-0a40-4792-80e2-e3bdf21baf4e";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/a4c75369-0a40-4792-80e2-e3bdf21baf4e";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  swapDevices = [
    { device = "/swapfile";
      size = 64 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  hardware.graphics.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
